### ISSUE TITLE
always loading

### ISSUE THREAD

**Issue by MTCherish** [ts-pro/vue-eternal-loading#10]
If the length of the list does not reach the scroll bar, the loading state will always be displayed, and the load function will not be triggered。
如果列表长度未达到滚动条情况下，会一直显示loading态，并且不会触发load函数

**Comment by gavrashenko** [comment]
Hello, thanks for the report. 
Could you provide a reproduction demo please? Because, I can't reproduce the issue for myself.

**Comment by gavrashenko** [comment]
Closed, until reproduction code is created.
