### ISSUE TITLE
electron 环境下无法触发加载

### ISSUE THREAD

**Issue by chf-gh** [ts-pro/vue-eternal-loading#14]
electron 环境下下面的isSSR得到的结果是true，导致div没有渲染，整个加载没有执行。
```
const isSSR =
  typeof process !== 'undefined' &&
  process.env !== undefined &&
  process.env.NODE_ENV !== 'test';
```
![image](https://user-images.githubusercontent.com/20312535/230594278-728a85c5-c2c6-46cb-ac12-457a83f08409.png)

**Comment by gavrashenko** [comment]
Hey, @chf-gh.

Thanks for the reporting. You issue should be fixed in [1.3.1 version](https://www.npmjs.com/package/@ts-pro/vue-eternal-loading?activeTab=readme)
