### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by RadoslawKopec93** [ts-pro/vue-eternal-loading#16]
Hello everything works pretty good while normal compilation. But when I tried to do yarn build I got and issue :
![image](https://github.com/ts-pro/vue-eternal-loading/assets/63808470/cb5faade-a6b3-4102-bdbe-ea78aabb8fd3)

Anybody had this problem before? I try to resolved by normal methods, but still main.ts don't see this component while build.

**Comment by gavrashenko** [comment]
Hello, @AABobi. 

Could you provide a reproduction demo, please?
