### ISSUE TITLE
Where i can find the TYPES?

### ISSUE THREAD

**Issue by phantodev** [ts-pro/vue-eternal-loading#18]
I have this error in my app:

Could not find a declaration file for module '@ts-pro/vue-eternal-loading'. 'c:/Users/eduardo.burko/Documents/portal-correto-final/travelfront-portal/node_modules/@ts-pro/vue-eternal-loading/dist/vue-eternal-loading.mjs' implicitly has an 'any' type.
  There are types at 'c:/Users/eduardo.burko/Documents/portal-correto-final/travelfront-portal/node_modules/@ts-pro/vue-eternal-loading/src/main.ts', but this result could not be resolved when respecting package.json "exports". The '@ts-pro/vue-eternal-loading' library may need to update its package.json or typings.
  
  Can you help me please?

**Comment by gavrashenko** [comment]
Hi, @phantodev. Thanks for reaching out.

Could you provide an example of code where you import a library and encounter the error? Are you facing this error during the build or in an IDE linter? Or provide a reproducible demo if possible to identify and fix the issue in a short term.
