### ISSUE TITLE
Found non-callable @@iterator

### ISSUE THREAD

**Issue by littlecxm** [ts-pro/vue-eternal-loading#2]
Uncaught (in promise) TypeError: Found non-callable @@iterator at Proxy.load (explore.vue:131)

when i use the components, just reference by [demo](https://ts-pro.github.io/vue-eternal-loading/guide/simple-usage.html#typescript) 

![image](https://user-images.githubusercontent.com/16154023/140052835-9bda12e6-882b-469d-b6f4-c07acb321821.png)

```ts
let page = 1;
const PAGE_SIZE = 30;
const load = async ({ loaded }: LoadAction) => {
  const loadedGames = await getListApi();
  gameList.value.push(...loadedGames);
  page += 1;
  loaded(loadedGames.length, PAGE_SIZE);
};
```

**Comment by gavrashenko** [comment]
It looks like that it's an error on your spread line `...loadedGames` but not a part of the **vue-eternal-loader** library. Try to check what's inside `loadedGames` it should be an array to apply spread to it, if not - that is the reason why you get this error.

To be more precise I need reproduction link with error.
