### ISSUE TITLE
Issue when building for production with Vite

### ISSUE THREAD

**Issue by ahudovich** [ts-pro/vue-eternal-loading#3]
I encountered a strange behaviour when migrating a large app to Vite. Recreated it in a demo app.

**Demo:** https://vue-eternal-loading-vite-test.surge.sh/
**Sources:** https://github.com/andgudovich/vue-eternal-loading-vite-test

There are 2 identical pages in the demo.
If we click "Cats 2" link first, the library won't be loaded on this page.
But if we open "Cats 1" page and then "Cats 2" - everything works fine.

1. The issue depends on the order in routes array and on the usage of `component: () => import('@/views/PageName.vue')`.
2. This problem isn't present on localhost.
3. Vite's build target is the lowest possible - "es2015". Changing the target is not helping.
4. No errors/warnings in the console

**Comment by gavrashenko** [comment]
@andgudovich Hello, and thanks for your report.

I've watched your demo and it seems like it's not a VueEternalLoading bug.

Like you described the problem appears in production build and vite uses rollup for it under the hood, so we have to look in that way. If we look at dependencies in `dist` folder, we will find out that the problem is with chunks. Try to fix it adding `rollupOptions` manually:
```
build: {
    target: 'es2015',
    cssCodeSplit: false,
    rollupOptions: {
      output: {
        manualChunks(id) {
          if (id.includes('node_modules')) {
            return 'vendor';
          }
        }
      }
    }
  },
```
But you can configure it for your own need of course.

**Comment by lptai** [comment]
I got the same issue when using vue3 + vite.
Solved as @gavrashenko suggest or like below if you want to split into smaller bundle files.

```
manualChunks: {
            'vue-renderer': ['vue'], // other bundles
            'vendor': ['@ts-pro/vue-eternal-loading']
          },
```

**Comment by ahudovich** [comment]
Thanks @gavrashenko and @lptai! `manualChunks` solves the issue.

As I noticed, for some reason Vite/Rollup put the library code into the first component file that uses it (`CatsDesc`). 

Before:

![image](https://user-images.githubusercontent.com/3611940/143940744-aac61969-920c-49a9-abfc-de6614a4b721.png)

After with `manualChunks` enabled:

![image](https://user-images.githubusercontent.com/3611940/143940782-6c610037-09dd-4f3c-a1d3-56a5769e5621.png)

**Comment by ahudovich** [comment]
@gavrashenko Any thoughts on releasing a version that will include esm? The problem is in that Vue CLI still doesn't support esm bundles in library mode, right?

**Comment by gavrashenko** [comment]
@andgudovich you're right. 

It's rather webpack 4 limitation which is used in vue-cli 4. They've added module experimental support in webpack 5 ( https://github.com/webpack/webpack/issues/2933#issuecomment-774253975 ) and we could try it in vue-cli 5 ( still in RC stage ).

**Comment by Hartaj-Singh-Dev** [comment]
Hi , I am also working on one of my project with vite in it , whenever I run "yarn build" , it creates only dist file with my assets and index.html . there is no js and no CSS . i am not understanding then how will it gonna work in production
