### ISSUE TITLE
Replace div with template for better flexibility?

### ISSUE THREAD

**Issue by yoshihikoueno** [ts-pro/vue-eternal-loading#9]
Hi! Thank you for the great project.
I found this project very useful but while using it, I got a suggestion that could possibly improve the flexibility.

https://github.com/ts-pro/vue-eternal-loading/blob/2adf928249591d988fe939fa98d8eefd8e10134c/src/components/VueEternalLoading/VueEternalLoading.vue#L2
Could we replace the `<div>` surrounding the content of `<slot>` with `<template>` so that we have an option not to have a `<div>` around the `<slot>` content?

Currently, I'm trying to implement a lazily loading table with this module, but I can't have the "loading" slot as a row for the table because of the `<div>` around the "loading" slot content.
So I thought it would be really cool if we can freely decide which tag to use for the "loading" slot.

Let me know if a sample code will help better describe the situation.
Best regards,

**Comment by gavrashenko** [comment]
Hello @yoshihikoueno, thanks for the proposal. 
Great idea.
